Feat: Add function for creating an empty state component
Appsilon/shiny.emptystate pull request #22
Opened 2023-05-23 07:47 UTC by vibalre

*Have you read the [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md)?*

Closes #21 

## Changes description

* Adds utility function `empty_state_component()` for creating a generic empty state component.
* Adds a default empty state component when `html_content = NULL`.

2023-05-23 11:04 UTC, vibalre reviewed
My suggested approach for a function to create an empty state component with a basic layout.

2023-05-23 11:32 UTC, rszymanski commented on R/empty_state.R
> +        )
I like how you added a screenshot of the example 💯 

I feel like the icon got a bit distorted (it's stretch in width). I suggest using suggested sizes from the [sizing classes from `fontawesome`](https://fontawesome.com/docs/web/style/size) instead.

```r
fontawesome::fa(
    name = "clipboard-question",
    height = "10rem"
)
```

Skipping the width allows the icon to keeps its original proportions.


This is how it looks like:
<img width="590" alt="image" src="https://github.com/Appsilon/shiny.emptystate/assets/83692505/60f7bb04-21cd-4f54-8801-5c26a709cf00">

What do you think?

2023-05-23 11:39 UTC, rszymanski commented on R/component.R
**Suggestion:**

Maybe we can add an example for using `bsicons` in the function documentation as well?

Also we can get it to work with `shiny::icon` as long as dependencies get rendered get included in the shiny app see example:

```r
library(shiny)
library(shiny.emptystate)

ui <- fluidPage(
  use_empty_state(),
  fontawesome::fa_html_dependency(),
  div(id = "a", style = "height: 300px")
)

server <- function(input, output, session) {
  es <- EmptyStateManager$new(
    id = "a",
    html_content = empty_state_component(
      shiny::icon(name = "book", class = "fa-10x"),
      title = "",
      subtitle = "Content is not available"
    )
  )
  
  es$show()
  
}

shinyApp(ui, server)
```

Do you think we should document that as well (that if your empty state component requires some html dependencies than those need to be included in the UI)?

2023-05-23 11:53 UTC, rszymanski commented on tests/testthat/test-component.R
> +})
**Requested Change / To Discuss**

I believe we can test additional behaviour like:
1. are we creating an element containing the provided title
2. are we creating an element containing the provided subtitle
3. are we creating an element containing the provided content

A test for 1 could be:

```r
  it("should include the title in the created element", {
    # Arrange
    component_title <- "My Title"

    # Act
    component <- empty_state_component(content = "", title = component_title)

    # Assert
    expect_true(contains_node_with_text(html_tag, component_title))
  })
```

where `contains_node_with_text` is:

```r
contains_node_with_text <- function(html_tag, text) {
  htmltools::tagQuery(component)$
    find("*")$
    filter(function(x, i) {
      if (is.null(x$children[[1]])) {
        FALSE
      } else {
        x$children[[1]] == text
      }
    })$length() == 1
}
```

2023-05-23 11:58 UTC, rszymanski commented on R/empty_state.R
> +        )
**Suggestion:**

What do you think about extracting this into a function `default_empty_state_component` and passing it as default argument?

I think it improves readability as we don't have html creation code nested in the `EmptyStateManager` class.

What do you think?

2023-05-23 11:58 UTC, rszymanski requested changes
See comments

2023-05-24 06:06 UTC, vibalre commented on R/empty_state.R
> +        )
Agree. Only height should be set now.

2023-05-24 06:20 UTC, vibalre commented on R/component.R
Thank you for clarifying on how to use `shiny::icon()`.  I think one advantage of using `shiny::icon()` over `fontawesome::fa()` is if they want to use `lib = "glyphicon"`, which does not require any html dependency it seems.

I mentioned this as a detail in the documentation and added an example using `bsicons`.

```
#' @details
#' `content` works best with [fontawesome::fa()] and [bsicons::bs_icon()].
#' [shiny::icon()] will also work, but this will require loading the
#' html dependencies in the ui, i.e. calling [fontawesome::fa_html_dependency()]
#' to use icons from FontAwesome.Glyphicon does not need any html dependency.
#'
#'
#' @examples
#'
#' library(shiny.emptystate)
#'
#' if (interactive()) {
#'   empty_state_component(
#'     fontawesome::fa(name = "clipboard-question", height = "10rem"),
#'     title = "Content is not available",
#'     subtitle = "Please provide valid inputs to generate content."
#'   )
#'
#'   empty_state_component(
#'     bsicons::bs_icon(
#'       name = "question-square",
#'       height = "15rem"
#'     ),
#'     title = "Content is not available",
#'     subtitle = "Please provide valid inputs to generate content."
#'   )
#' }
```

2023-05-24 06:22 UTC, vibalre commented on R/empty_state.R
> +        )
Agree. I created a new internal function `default_empty_state_component`, and it does look cleaner as a default `html_content`.

2023-05-24 07:53 UTC, rszymanski commented on R/component.R
> +#'       height = "15rem"
Shouldn't it be `size` instead of `height`? 🤔 

```suggestion
#'       size = "15rem"
```

2023-05-24 07:56 UTC, rszymanski commented on tests/testthat/test-component.R
> +})
I am fine with this approach! 👍

2023-05-24 07:59 UTC, rszymanski approved these changes
Added one more comment (If I recall correctly `bsicons` uses a `size` argument not `height`)

I see CI is failing (it's complaining about a WORDLIST).

Approving - please double check if it is `size` or `height` for `bsicons`, update the WORDLIST and if CI passes, then happy merging! 😃

2023-05-24 08:13 UTC, vibalre commented on R/component.R
> +#'       height = "15rem"
Yes. `size` is the correct argument to use here. 😅

2023-05-24 08:19 UTC, merged