Feat: Adds first draft for use image tutorial
Appsilon/shiny.emptystate pull request #25
Opened 2023-05-24 11:31 UTC by vibalre

*Have you read the [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md)?*

Closes #23

## Changes description

* Adds vignette on how to use images in for empty state content.

2023-05-24 11:46 UTC, vibalre reviewed
A very straight forward vignette with some example code for both vanilla Shiny and Rhino.

2023-05-24 11:46 UTC, vibalre commented on .github/workflows/main.yml
> +
Pipeline was failing in [Windows and mac because Pandoc](https://github.com/Appsilon/shiny.emptystate/actions/runs/5067640036) is missing. 

I tried adding `vignettes` to `.Rbuildignore` [like in Rhino](https://github.com/Appsilon/rhino/blob/main/.Rbuildignore), but I got an error that `vignettes` is [required since `R 3.1.0`.](https://github.com/Appsilon/shiny.emptystate/actions/runs/5067957502/jobs/9099641094).

I found this [step in `shiny.semantic`.](https://github.com/Appsilon/shiny.semantic/blob/4b00b7c294012783e8fe80547f9ace9abf1d2214/.github/workflows/main.yml#L32). Workflow is passing with this step, but we should change this if there is a better solution.

2023-05-25 09:32 UTC, rszymanski commented on vignettes/use-undraw-drawkit-image.Rmd
> +unDraw allows for direct download of images, as `svg` or `png`. DrawKit requires an e-mail where they will send the download link for the selected set of images.
Maybe let's just add a note that before using those services check their licenses?

Their license can change and our vignette would become outdated.

What do you think about rephrasing it to:

```suggestion
> **Important:** Before using illustrations from the mentioned services, please get acquainted with their respective licenses: [DrawKit License](https://www.drawkit.com/license), [unDraw License](https://undraw.co/license)
```

2023-05-25 09:42 UTC, rszymanski commented
What do you think about updating the [README example](https://github.com/Appsilon/shiny.emptystate/tree/doc/add-tutorial-use-images/man) with the gif we use in the tutorial?

2023-05-25 09:47 UTC, rszymanski commented
The vignette doesn't show in the pkgdown site:
![image](https://github.com/Appsilon/shiny.emptystate/assets/83692505/987f4d2d-0160-49e4-92cc-561aaeba5846)

I see we are using some customization in pkgdown - perhaps we can reuse the setup from [shiny.router](https://github.com/Appsilon/shiny.router/blob/main/pkgdown/_pkgdown.yml) - @jakubnowicki is probably the best person to ask about this ;)

2023-05-25 09:48 UTC, rszymanski requested changes
See comments

2023-05-25 09:57 UTC, jakubnowicki commented
> **Requested Change:**
> 
> The vignette doesn't show in the pkgdown site: ![image](https://user-images.githubusercontent.com/83692505/240873747-987f4d2d-0160-49e4-92cc-561aaeba5846.png)
> 
> I see we are using some customization in pkgdown - perhaps we can reuse the setup from [shiny.router](https://github.com/Appsilon/shiny.router/blob/main/pkgdown/_pkgdown.yml) - @jakubnowicki is probably the best person to ask about this ;)

Since this is just a single tutorial, I suggest something similar to `shiny.benchmark`: https://github.com/Appsilon/shiny.benchmark/blob/main/pkgdown/_pkgdown.yml#L38

2023-05-25 12:13 UTC, vibalre commented on vignettes/use-undraw-drawkit-image.Rmd
> +      tags$link(rel = "stylesheet", type = "text/css", href = "styles.css")
I agree. I opted for inline CSS. It is about 37 lines of css code, so I think it is worth making the example self-contained.

2023-05-25 12:16 UTC, vibalre commented on pkgdown/_pkgdown.yml
> +      text: "Tutorial"
Added this to include the tutorial section.

2023-05-25 12:16 UTC, vibalre commented on man/figures/file_upload_empty_state_example.gif
Kept the file name but changed the content.

2023-05-25 12:16 UTC, vibalre commented on vignettes/use-undraw-drawkit-image.Rmd
> +<img src="files/unDraw-empty-state-demo.gif" alt="shiny.emptystate element using image from unDraw" width=675px/>
I am not yet sure if this will get rendered properly. I tried to build the site locally, but it seems `pkgdown` is getting confused with the path.

2023-05-25 12:36 UTC, rszymanski approved these changes
Please address the pkgdown issue before merging ;)

2023-05-25 14:07 UTC, merged