Tests/29 add unit tests
Appsilon/shiny.emptystate pull request #31
Opened 2023-06-19 08:59 UTC by insightsurge

*Have you read the [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md)?* Yes

Closes #29 

## Changes description
Expanded unit test coverage for the package:
- **EmptyStateManager R6 Class:** 
   - Tests if the class has been instantiated
   - Tests if public members exists
   - Tests if private members exist
   - Tests if it can be cloned and cloned obj passes above tests.
   - Tests if the class is locked
- **use_empty_state():** There was not much I can do as the function takes no params (any suggestions are welcome)
   - Tests if source files (css and js) are added properly
   - Tests if dependencies are added properly

2023-06-20 07:01 UTC, jakubnowicki requested changes
This is a good start, but for `EmptyStateManager` you need to test the actual logic, not `R6` features. Please check comments for more details.

Also, if you want to use BDD (which is IMO a good approach), please use `describe` - `it` construction (instead of `test_that`) - more details [here](https://testthat.r-lib.org/reference/describe.html).

2023-06-28 12:26 UTC, insightsurge commented on tests/testthat/test-empty_state.R
> +  })
Make sense, I've removed this test in latest commit

2023-06-28 12:26 UTC, insightsurge commented on tests/testthat/test-empty_state.R
> +describe("EmptyStateManager", {
I've added additional tests to test the functioning of show and hide members.

2023-06-28 12:29 UTC, insightsurge commented on tests/testthat/test-empty_state.R
> +  }
I wanted to reuse those tests on cloned object too. But now that I've removed that test completely, there's no point in having these functions.

2023-07-11 09:40 UTC, jakubnowicki requested changes
Overall looks good. Most comments are the suggestions for the code style. Apart from that, only some minor tuning is required.

2023-07-11 09:40 UTC, jakubnowicki commented on tests/testthat/test-empty_state.R
> +                 as.character(default_empty_state_component()))
```suggestion
    expect_equal(
      test_class$.__enclos_env__$private$.html_content,
      as.character(default_empty_state_component())
    )
```

2023-07-11 09:40 UTC, jakubnowicki commented on tests/testthat/test-empty_state.R
> +                                        color = "navy")
```suggestion
    test_class <- EmptyStateManager$new("test_id", color = "navy")
```

2023-07-11 09:40 UTC, jakubnowicki commented on tests/testthat/test-empty_state.R
> +                 "navy")
```suggestion
    expect_equal(test_class$.__enclos_env__$private$.color, "navy")
```

2023-07-11 09:40 UTC, jakubnowicki commented on tests/testthat/test-empty_state.R
> +                 as.character(expected_div))
```suggestion
    expect_equal(
      app$get_html(selector = ".empty-state-content"),
      as.character(expected_div)
    )
```

2023-07-11 09:40 UTC, jakubnowicki commented on tests/testthat/test-empty_state.R
> +                    "emptystate.js")
```suggestion
  src_files <- list(
    "emptystate.css",
    "emptystate.js"
  )
```

2023-07-11 09:40 UTC, jakubnowicki commented on tests/testthat/test-empty_state.R
> +  it("checks if show functionality work when button is clicked", {
Please modify this description so it is more generic - the test is not about the button, but about the show functionality and if it works when triggered. It doesn't matter, what triggers it.

2023-07-11 09:40 UTC, jakubnowicki commented on tests/testthat/test-empty_state.R
> +  })
1) Same as for the "show" test - the description should state that the empty state component is hidden if not triggered.
2) This can be simplified - you don't need to specify the exact component, as it should be just NULL. You can use the same test as in the "hide" test.

2023-07-11 09:40 UTC, jakubnowicki commented on tests/testthat/setup-disable-crashpad.R
Please add a comment that describes the source of this file (as it was copied from `shinytest2`).

2023-07-11 09:40 UTC, jakubnowicki commented on tests/testthat/test-empty_state.R
> +  test_that("should add dependencies properly", {
```suggestion
  it("should add dependencies properly", {
```

2023-07-14 13:09 UTC, jakubnowicki requested changes
The CI passes, but logs show some errors:
https://github.com/Appsilon/shiny.emptystate/actions/runs/5553699568/jobs/10142568414#step:5:159
https://github.com/Appsilon/shiny.emptystate/actions/runs/5553699568/jobs/10142568641#step:5:159
https://github.com/Appsilon/shiny.emptystate/actions/runs/5553699568/jobs/10142568748#step:5:159
https://github.com/Appsilon/shiny.emptystate/actions/runs/5553699568/jobs/10142568882#step:5:154
https://github.com/Appsilon/shiny.emptystate/actions/runs/5553699568/jobs/10142568538#step:5:167

Also, the windows CI is not able to launch the browser (and the test is skipped):
https://github.com/Appsilon/shiny.emptystate/actions/runs/5553699568/jobs/10142568538#step:5:158

2023-07-17 07:32 UTC, insightsurge commented
Looks like manually disabling browser was causing issue, I've removed it and checks are passing now. Windows test which was skipping is also working fine now.

- **Mac:** https://github.com/Appsilon/shiny.emptystate/actions/runs/5572881630/jobs/10179425814#step:5:158
- **Win:** https://github.com/Appsilon/shiny.emptystate/actions/runs/5572881630/jobs/10179425973#step:5:160
- **Ubuntu devel:** https://github.com/Appsilon/shiny.emptystate/actions/runs/5572881630/jobs/10179426167#step:5:158
- **Ubuntu rel:** https://github.com/Appsilon/shiny.emptystate/actions/runs/5572881630/jobs/10179426281#step:5:158
- **Ubuntu oldrel:** https://github.com/Appsilon/shiny.emptystate/actions/runs/5572881630/jobs/10179426424#step:5:153

2023-07-17 13:55 UTC, jakubnowicki approved these changes
Great!

2023-07-17 13:56 UTC, merged