Documentation improvements
Appsilon/shiny.emptystate pull request #38
Opened 2023-07-18 10:19 UTC by insightsurge

*Have you read the [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md)?* Yes

Closes #35 

## Changes description
- EmptyStateManager Documentation updated.
  - Public members documentation updated, examples added.
  - Few examples are wrapped around `\dontrun{ }` specially examples for hide() and show().
  - Specified if a member doesn't return anything (like `show()` and `hide()`)
- Added 2 liner documentation for `default_empty_state_component()` as well.
- `LazyData` arg was removed from the DESCRIPTION file on purpose, as the package is not exporting any data.frame
- Misc:
   - Replaced `pkg::func()` calls with `@importFrom pkg func`
   - General order of roxygen tags is `@description , @param, @return, @details, @examples, @importForm, @export`

2023-07-18 10:25 UTC, insightsurge commented on DESCRIPTION
> -LazyData: true
I've removed it on purpose, please advise if this should be added back

2023-07-18 10:26 UTC, insightsurge commented on R/component.R
> +#' @importFrom htmltools tags
Removed :: and replaced it wth `@importFrom`

2023-07-18 10:27 UTC, insightsurge commented on R/empty_state.R
>  #' @export
The idea is not the add any example here. Added individual examples of public members instead

2023-07-18 14:16 UTC, jakubnowicki requested changes
Good direction, but please check my comments.

2023-07-18 14:16 UTC, jakubnowicki commented on R/empty_state.R
>  #' @export
I don't like this approach. As a result, it generates:
1. an example for each method without any context
2. a summary example which is not correct as it does not show how to use the class in a Shiny application.
The example should show a basic usage in a Shiny application. This can be e.g.  the application you created for e2e tests (https://github.com/Appsilon/shiny.emptystate/blob/main/tests/testthat/helper.R). Strip it from some parts required for the tests and enhance it with comments.

2023-07-18 14:16 UTC, jakubnowicki commented on R/component.R
> +#' @returns a shiny.tag.
```suggestion
#' @returns a shiny.tag
```

2023-07-18 14:16 UTC, jakubnowicki commented on R/component.R
>  #' @return a shiny.tag.
```suggestion
#' @return a shiny.tag
```

2023-07-18 14:16 UTC, jakubnowicki commented on R/component.R
> +#' main content for the empty state.
```suggestion
#' @param content An HTML tag object used to render and provide
#' the main content for the empty state.
```

2023-07-19 08:56 UTC, insightsurge commented on R/empty_state.R
>  #' @export
Make sense, I've added an app `@example` with comments, and removed `@examples` of public members as autogenerated `@usage` was enough for public members and detailed instructions are already covered in the shiny app example.

2023-07-19 09:53 UTC, jakubnowicki requested changes
Please check my comments

2023-07-19 09:53 UTC, jakubnowicki commented on R/empty_state.R
> +#'       if (manager_object$is_empty_state_show()) {
This is redundant, `hide` method checks if the component is visible: https://github.com/Appsilon/shiny.emptystate/blob/main/R/empty_state.R#L59

2023-07-19 09:53 UTC, jakubnowicki commented on R/empty_state.R
> +#'       manager_object$show()
```suggestion
#'       # Show empty state
#'       manager_object$show()
```

2023-07-19 09:53 UTC, jakubnowicki commented on R/empty_state.R
> +#'         # Hide empty state using `manager_object$hide()`
```suggestion
#'         # Hide empty state
```

2023-07-19 09:53 UTC, jakubnowicki commented on R/empty_state.R
> +#'     shiny::tableOutput("my_table")
```suggestion
#'     actionButton("show", "Show empty state!"),
#'     actionButton("hide", "Hide empty state!"),
#'     tableOutput("my_table")
```

2023-07-19 11:44 UTC, jakubnowicki approved these changes
LGTM

2023-07-19 11:44 UTC, merged